### ISSUE TITLE
Plugin for NetBeans 8.1?

### ISSUE THREAD

**Issue by juliocoliveira** [jGauravGupta/js-css-minify-compress#18]
Hi guys, can you please upload this for NetBeans 8.1?

**Comment by AllanAndrade** [comment]
Please, upload this for NetBeans 8.1!!!

**Comment by jGauravGupta** [comment]
Sure, release will be available soon for 8.1

**Comment by jGauravGupta** [comment]
Please download the plugin [http://plugins.netbeans.org/plugin/49666/js-css-minify-compress](http://plugins.netbeans.org/plugin/49666/js-css-minify-compress)
